### PR TITLE
Updated FFmpeg library source and binary to 4.0

### PR DESCRIPTION
**Pull request by ponnex**
Supports FFprobe

### CODE REVIEW

**Comment by MichaelSolati** [comment]
@ponnex ooooh, I'll have to take a look at this in the next day or two. Thank you for the PR though! (If everything is good I'll have this in and published by Sunday)

**Comment by ponnex** [comment]
Found this for IOS -> https://github.com/icarofm/ffmpeg-cmd-ios
Would like to work with you on this so that we could bring ffmpeg working on both Android and IOS on Nativescript

**Comment by ponnex** [comment]
As well as this for IOS -> https://github.com/iswear/ffmpeg_for_ios_with_commandline

**Comment by MichaelSolati** [comment]
Dude, I'm down for the help and expanding the package. My schedule had gotten swamped because of a change of location/jobs as well as needing to manage another package. Uhmm, I have my email on my profile, if you want to shoot me an email we can coordinate for this.

**Comment by ponnex** [comment]
Oh I see that's unfortunate dude, will be working on this so might be submitting PR's from time to time. ;)

**Pull request merged**
